// Asserts every golden vector byte for byte (plan §4.1, §6 W0 done criterion).
// The vectors are generated by contracts/cmd/vectors from the normative Go
// derivations; this proves the TS derivations reproduce them exactly.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { describe, it, expect } from 'vitest';

import { digestBytes, canonicalDigest, manifestSchema } from '../src/types.js';
import * as version from '../src/version.js';
import * as ref from './reference.js';

const vectorsPath = fileURLToPath(new URL('../testdata/vectors.json', import.meta.url));
const V = JSON.parse(readFileSync(vectorsPath, 'utf8'));

describe('blobDigest (deploy.DigestBytes)', () => {
  it('matches every vector', () => {
    for (const v of V.blobDigest) {
      expect(digestBytes(Buffer.from(v.input, 'utf8'))).toBe(v.digest);
    }
  });
});

describe('canonicalDigest (deploy.Manifest.CanonicalDigest)', () => {
  it('matches every vector', () => {
    for (const v of V.canonicalDigest) {
      const m = manifestSchema.parse(v.manifest);
      expect(canonicalDigest(m)).toBe(v.digest);
    }
  });
});

describe('deployId (deploysvc.deriveDeployID)', () => {
  it('matches every vector, and canonicalDigest agrees', () => {
    for (const v of V.deployId) {
      const m = manifestSchema.parse(v.manifest);
      expect(canonicalDigest(m)).toBe(v.canonicalDigest);
      expect(ref.deriveDeployId(v.appId, m)).toBe(v.deployId);
    }
  });
});

describe('fingerprint (deploysvc.fingerprint)', () => {
  it('matches every vector', () => {
    for (const v of V.fingerprint) {
      expect(ref.fingerprint(v.gitRemote, v.slug)).toBe(v.fingerprint);
    }
  });
});

describe('urlToken (deploysvc.urlToken)', () => {
  it('matches every vector', () => {
    for (const v of V.urlToken) {
      const tok = ref.urlToken(v.appId);
      expect(tok).toBe(v.token);
      expect(tok).toMatch(/^[0-9a-z]{10}$/);
    }
  });
});

describe('cfHash (cloudflare.cfHash)', () => {
  it('matches every vector and is 32 hex chars', () => {
    for (const v of V.cfHash) {
      const h = ref.cfHash(v.salt, v.digest);
      expect(h).toBe(v.hash);
      expect(h).toMatch(/^[0-9a-f]{32}$/);
    }
  });
});

describe('cacheKey (next.cacheKey)', () => {
  it('matches every vector', () => {
    for (const v of V.cacheKey) {
      expect(ref.cacheKey(v.rel)).toBe(v.key);
    }
  });
});

describe('collapseSlashes (next.collapseSlashes)', () => {
  it('matches every vector', () => {
    for (const v of V.collapseSlashes) {
      expect(ref.collapseSlashes(v.in)).toBe(v.out);
    }
  });
});

describe('slug sanitize (deploysvc.sanitizeSlug)', () => {
  it('matches every vector', () => {
    for (const v of V.slug) {
      expect(ref.sanitizeSlug(v.raw)).toBe(v.slug);
    }
  });
});

describe('user code (api normalize/display/alphabet)', () => {
  it('normalize + display match every vector', () => {
    for (const v of V.userCodeNormalize) {
      const norm = ref.normalizeUserCode(v.input);
      expect(norm).toBe(v.normalized);
      expect(ref.displayUserCode(norm)).toBe(v.display);
    }
  });

  it('alphabet maps every byte value', () => {
    expect(ref.USER_CODE_ALPHABET).toBe(V.userCodeAlphabet.alphabet);
    for (const m of V.userCodeAlphabet.map) {
      expect(ref.userCodeChar(m.byte)).toBe(m.char);
    }
  });
});

describe('version (version.Valid / version.Compare)', () => {
  it('valid() matches every vector', () => {
    for (const v of V.versionValid) {
      expect(version.valid(v.v)).toBe(v.valid);
    }
  });

  it('compare() matches every vector', () => {
    for (const v of V.versionCompare) {
      expect(version.compare(v.a, v.b)).toBe(v.cmp);
    }
  });
});

describe('id formats', () => {
  it('match the frozen prefixes and hex lengths', () => {
    expect(V.idFormats.app).toEqual({ prefix: 'app_', hexBytes: 6, hexChars: 12 });
    expect(V.idFormats.account).toEqual({ prefix: 'acct_', hexBytes: 9, hexChars: 18 });
    expect(V.idFormats.clientRef).toEqual({ prefix: 'cr_', hexBytes: 16, hexChars: 32 });
  });
});
