// The container buildpack: it turns a project directory into a container build
// context — the source files plus a generated Dockerfile and entrypoint — that
// the platform builds and runs unchanged. This replaces the OpenNext translation:
// nothing rewrites the app; it runs as a plain Node process listening on a port,
// exactly as it runs elsewhere.
//
// A user Dockerfile at the repo root is the escape hatch: 280 uses it as-is and
// generates nothing. Otherwise the buildpack generates the Dockerfile for the
// detected stack. Either way the manifest is a build-context descriptor
// (contracts Manifest): kind "container", a BuildSpec, and every context file
// content-addressed so the deploy loop uploads only what the server lacks.

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import {
  MANIFEST_KIND_CONTAINER,
  digestBytes,
  normalizeEgressPolicy,
  type BlobInfo,
  type Digest,
  type EgressPolicy,
  type Manifest,
} from '@280/contracts';
import type { Bundle } from './static.js';
import { fail, fileExists, walkContext } from './walk.js';

const EMPTY_EGRESS: EgressPolicy = { allowedHosts: [], credentials: [] };

// read280Egress lifts the app's outbound allowlist out of 280.json. The whole
// egress contract is declarative: `allow` names the hosts the app may reach and
// `credentials` binds a host to a 280 secret the platform attaches in-flight (the
// app holds no keys). Absent 280.json or egress block => default-deny (reach
// nothing). A malformed block fails preflight so the author fixes it before deploy.
function read280Egress(root: string): EgressPolicy {
  const path = join(root, '280.json');
  if (!fileExists(path)) return EMPTY_EGRESS;
  let parsed: unknown;
  try {
    parsed = JSON.parse(readFileSync(path, 'utf8'));
  } catch {
    fail('280.json is not valid JSON', 'fix the JSON syntax in 280.json, then run 280 push again');
  }
  const egress = (parsed as { egress?: unknown }).egress;
  if (egress === undefined || egress === null) return EMPTY_EGRESS;
  if (typeof egress !== 'object') {
    fail('280.json "egress" must be an object', 'set "egress": { "allow": [...], "credentials": [...] }');
  }
  const e = egress as { allow?: unknown; allowedHosts?: unknown; credentials?: unknown };
  const allow = e.allow ?? e.allowedHosts ?? [];
  if (!Array.isArray(allow) || allow.some((h) => typeof h !== 'string')) {
    fail('280.json egress.allow must be a list of host strings', 'e.g. "allow": ["api.stripe.com", "*.supabase.co"]');
  }
  const rawCreds = e.credentials ?? [];
  if (!Array.isArray(rawCreds)) {
    fail('280.json egress.credentials must be a list', 'e.g. "credentials": [{ "host": "api.stripe.com", "secret": "STRIPE_KEY" }]');
  }
  const credentials = rawCreds.map((c, i) => {
    const cred = c as { host?: unknown; secret?: unknown; header?: unknown; scheme?: unknown };
    if (typeof cred.host !== 'string' || typeof cred.secret !== 'string') {
      fail(`280.json egress.credentials[${i}] needs a "host" and a "secret" name`, 'e.g. { "host": "api.stripe.com", "secret": "STRIPE_KEY" }');
    }
    return {
      host: cred.host,
      secret: cred.secret,
      header: typeof cred.header === 'string' ? cred.header : 'authorization',
      scheme: typeof cred.scheme === 'string' ? cred.scheme : 'Bearer',
    };
  });
  return normalizeEgressPolicy({ allowedHosts: allow as string[], credentials });
}

// APP_PORT is the port the platform routes to and the buildpack makes the app
// listen on. It is also the container class's defaultPort — the two must agree.
export const APP_PORT = 8080;

// CA_PATH is where Cloudflare mounts the ephemeral per-instance CA at runtime. The
// entrypoint installs it before the app starts so platform-injected HTTPS egress
// is trusted; it cannot be baked into the image (it only exists at runtime).
const CA_PATH = '/etc/cloudflare/certs/cloudflare-containers-ca.crt';

// ENTRYPOINT installs the runtime CA (platform egress, phase 3) and then execs the
// app. Locked platform behaviour, generated into every buildpack image so app
// authors never handle it. A no-op when the CA is absent (e.g. local docker run).
const ENTRYPOINT = `#!/bin/sh
set -e
CA="${CA_PATH}"
if [ -f "$CA" ]; then
  cp "$CA" /usr/local/share/ca-certificates/cf-containers-ca.crt 2>/dev/null || true
  update-ca-certificates >/dev/null 2>&1 || true
  export NODE_EXTRA_CA_CERTS="$CA"
fi
exec "$@"
`;

const ENTRYPOINT_PATH = 'entrypoint.280.sh';

// NEXT_DOCKERFILE builds and runs a Next.js app from source, unchanged: install,
// `next build`, `next start` on APP_PORT. No standalone-output requirement and no
// adapter — the container is the app's own runtime.
const NEXT_DOCKERFILE = `# syntax=docker/dockerfile:1
# Generated by 280. Runs your Next.js app unchanged in a container.
FROM node:20-bookworm-slim
WORKDIR /app
ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1 PORT=${APP_PORT} HOSTNAME=0.0.0.0
RUN apt-get update \\
 && apt-get install -y --no-install-recommends ca-certificates \\
 && rm -rf /var/lib/apt/lists/*
COPY package.json package-lock.json* ./
RUN if [ -f package-lock.json ]; then npm ci; else npm install; fi
COPY . .
RUN npm run build
RUN cp ${ENTRYPOINT_PATH} /280-entrypoint.sh && chmod +x /280-entrypoint.sh
EXPOSE ${APP_PORT}
ENTRYPOINT ["/280-entrypoint.sh"]
CMD ["npm", "run", "start"]
`;

// STATIC_DOCKERFILE serves a prebuilt static site with a tiny embedded Node
// server (no build-time network, no npm install), so a static project also runs
// as a plain container.
const STATIC_DOCKERFILE = `# syntax=docker/dockerfile:1
# Generated by 280. Serves your static site from a container.
FROM node:20-bookworm-slim
WORKDIR /app
ENV NODE_ENV=production PORT=${APP_PORT}
RUN apt-get update \\
 && apt-get install -y --no-install-recommends ca-certificates \\
 && rm -rf /var/lib/apt/lists/*
COPY . .
RUN cp ${ENTRYPOINT_PATH} /280-entrypoint.sh && chmod +x /280-entrypoint.sh
EXPOSE ${APP_PORT}
ENTRYPOINT ["/280-entrypoint.sh"]
CMD ["node", "/app/server.280.mjs"]
`;

const STATIC_SERVER = `import { createServer } from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { join, normalize, extname } from 'node:path';

const ROOT = process.cwd();
const PORT = Number(process.env.PORT) || ${APP_PORT};
const TYPES = {
  '.html': 'text/html; charset=utf-8', '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8', '.mjs': 'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8', '.svg': 'image/svg+xml',
  '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.gif': 'image/gif',
  '.webp': 'image/webp', '.ico': 'image/x-icon', '.woff2': 'font/woff2', '.txt': 'text/plain; charset=utf-8',
};

async function resolve(urlPath) {
  const clean = normalize(decodeURIComponent(urlPath.split('?')[0])).replace(/^(\\.\\.[/\\\\])+/, '');
  let p = join(ROOT, clean);
  try {
    if ((await stat(p)).isDirectory()) p = join(p, 'index.html');
    return p;
  } catch {
    return join(ROOT, 'index.html'); // SPA fallback
  }
}

createServer(async (req, res) => {
  try {
    const file = await resolve(req.url || '/');
    const body = await readFile(file);
    res.writeHead(200, { 'content-type': TYPES[extname(file)] || 'application/octet-stream' });
    res.end(body);
  } catch {
    res.writeHead(404, { 'content-type': 'text/plain' });
    res.end('not found');
  }
}).listen(PORT, '0.0.0.0', () => console.log('280 static server on', PORT));
`;

// IGNORE_DIRS are never uploaded: build outputs and dependency/VCS trees the image
// rebuilds itself, kept out so the context stays small and deterministic.
const IGNORE_DIRS = new Set([
  'node_modules',
  '.git',
  '.next',
  '.280',
  '.vercel',
  '.turbo',
  '.cache',
]);

// skipRepo drops ignored trees and, importantly, secret files: a .env* must never
// leave the machine or enter the image. Platform-held secrets are phase 3; until
// then the safe default is to never ship them.
function skipRepo(rel: string, isDir: boolean): boolean {
  const base = rel.split('/').pop() ?? '';
  if (isDir) return IGNORE_DIRS.has(base);
  return base === '.env' || base.startsWith('.env.');
}

// bytes content-addresses one generated file and appends it to the context.
function addGenerated(
  files: BlobInfo[],
  content: Map<Digest, Uint8Array>,
  path: string,
  text: string,
): void {
  const data = new TextEncoder().encode(text);
  const dig = digestBytes(data);
  content.set(dig, data);
  files.push({ path, digest: dig, size: data.length });
}

function assemble(
  files: BlobInfo[],
  content: Map<Digest, Uint8Array>,
  builder: string,
  notes: string[],
  egress: EgressPolicy = EMPTY_EGRESS,
): Bundle {
  if (files.length === 0) {
    fail('the build context is empty', 'build your app first, then run 280 push again');
  }
  const manifest: Manifest = {
    kind: MANIFEST_KIND_CONTAINER,
    build: { builder, dockerfile: 'Dockerfile', port: APP_PORT },
    files,
    egress,
  };
  const out = egress.allowedHosts.length
    ? [...notes, `egress allowlist: ${egress.allowedHosts.join(', ')} (everything else is blocked)`]
    : notes;
  return { manifest, content, notes: out };
}

// buildNextContainer assembles the context for a Next.js project.
export function buildNextContainer(root: string): Bundle {
  if (!fileExists(join(root, 'package.json'))) {
    fail(
      'no package.json found for this Next.js project',
      'run 280 push from your app directory (the one with package.json)',
    );
  }
  const content = new Map<Digest, Uint8Array>();
  const egress = read280Egress(root);

  // Escape hatch: a user Dockerfile at the repo root wins, and 280 generates
  // nothing — the app is built exactly as its Dockerfile says.
  if (fileExists(join(root, 'Dockerfile'))) {
    const files = walkContext(root, content, { skip: skipRepo });
    return assemble(
      files,
      content,
      'dockerfile',
      [
        'using your Dockerfile; your app must listen on port ' + APP_PORT,
        'to allow platform HTTPS egress, install the Cloudflare CA in your entrypoint (' + CA_PATH + ')',
      ],
      egress,
    );
  }

  const files = walkContext(root, content, { skip: skipRepo });
  addGenerated(files, content, 'Dockerfile', NEXT_DOCKERFILE);
  addGenerated(files, content, ENTRYPOINT_PATH, ENTRYPOINT);
  return assemble(
    files,
    content,
    'next',
    ['generated a Dockerfile that builds and runs your Next.js app on port ' + APP_PORT],
    egress,
  );
}

// buildStaticContainer assembles the context for a prebuilt static site: the
// built directory, plus the generated server, Dockerfile, and entrypoint.
export function buildStaticContainer(root: string, dir: string): Bundle {
  const content = new Map<Digest, Uint8Array>();
  const egress = read280Egress(root);

  if (fileExists(join(dir, 'Dockerfile'))) {
    const files = walkContext(dir, content, { skip: skipRepo });
    return assemble(
      files,
      content,
      'dockerfile',
      ['using your Dockerfile; your app must listen on port ' + APP_PORT],
      egress,
    );
  }

  const files = walkContext(dir, content, { skip: skipRepo });
  addGenerated(files, content, 'server.280.mjs', STATIC_SERVER);
  addGenerated(files, content, 'Dockerfile', STATIC_DOCKERFILE);
  addGenerated(files, content, ENTRYPOINT_PATH, ENTRYPOINT);
  return assemble(
    files,
    content,
    'static',
    ['generated a container that serves your static site on port ' + APP_PORT],
    egress,
  );
}
