import { execFileSync } from 'node:child_process';
import { join } from 'node:path';
import {
  MANIFEST_KIND_CONTAINER,
  digestBytes,
  type BlobInfo,
  type Digest,
  type Manifest,
} from '@280/contracts';
import type { Bundle } from './static.js';
import type { ConfigEntry, IntegrationRequirement } from '@280/contracts';
import { read280, routeGateDiff, type Policy280 } from './manifest280.js';
import { discoverNextRoutes } from './nextroutes.js';
import { dirExists, fail, fileExists, walkContext } from './walk.js';
const EMPTY_POLICY: Policy280 = {
  egress: { allowedHosts: [], credentials: [] },
  access: 'invited',
  roles: [],
  routes: [],
  secrets: [],
  config: [],
  integrations: [],
};
export const APP_PORT = 8080;
const CA_PATH = '/etc/cloudflare/certs/cloudflare-containers-ca.crt';
const ENTRYPOINT = `#!/bin/sh
set -e
CA="${CA_PATH}"
if [ -f "$CA" ]; then
  cp "$CA" /usr/local/share/ca-certificates/cf-containers-ca.crt 2>/dev/null || true
  update-ca-certificates >/dev/null 2>&1 || true
  export NODE_EXTRA_CA_CERTS="$CA"
fi
exec "$@"
`;
const ENTRYPOINT_PATH = 'entrypoint.280.sh';
const INSTRUMENTATION_FILE = 'instrumentation.js';
const INSTRUMENTATION = `export function onRequestError(err, request, context) {
  try {
    console.error(
      JSON.stringify({
        t: '280.error',
        digest: err && err.digest ? String(err.digest) : '',
        message: err && err.message ? String(err.message) : String(err),
        stack: err && err.stack ? String(err.stack) : '',
        path: request && request.path ? request.path : '',
        routerKind: context && context.routerKind ? context.routerKind : '',
      }),
    );
  } catch {}
}
`;
const INSTRUMENTATION_NAMES = ['instrumentation.ts', 'instrumentation.js', 'instrumentation.mjs', 'instrumentation.tsx'];
const NEXT_DOCKERFILE = `# syntax=docker/dockerfile:1
# Generated by 280. Runs your Next.js app unchanged in a container.
FROM node:20-bookworm-slim
WORKDIR /app
ENV NODE_ENV=production NEXT_TELEMETRY_DISABLED=1 PORT=${APP_PORT} HOSTNAME=0.0.0.0
RUN apt-get update \\
 && apt-get install -y --no-install-recommends ca-certificates \\
 && rm -rf /var/lib/apt/lists/*
COPY package.json package-lock.json* ./
# --include=dev: NODE_ENV=production above makes npm omit devDependencies, but
# next build needs them (typescript for a next.config.ts, @types, etc.).
RUN if [ -f package-lock.json ]; then npm ci --include=dev; else npm install --include=dev; fi
COPY . .
RUN npm run build
RUN cp ${ENTRYPOINT_PATH} /280-entrypoint.sh && chmod +x /280-entrypoint.sh
EXPOSE ${APP_PORT}
ENTRYPOINT ["/280-entrypoint.sh"]
CMD ["npm", "run", "start"]
`;
const STATIC_DOCKERFILE = `# syntax=docker/dockerfile:1
# Generated by 280. Serves your static site from a container.
FROM node:20-bookworm-slim
WORKDIR /app
ENV NODE_ENV=production PORT=${APP_PORT}
RUN apt-get update \\
 && apt-get install -y --no-install-recommends ca-certificates \\
 && rm -rf /var/lib/apt/lists/*
COPY . .
RUN cp ${ENTRYPOINT_PATH} /280-entrypoint.sh && chmod +x /280-entrypoint.sh
EXPOSE ${APP_PORT}
ENTRYPOINT ["/280-entrypoint.sh"]
CMD ["node", "/app/server.280.mjs"]
`;
const STATIC_SERVER = `import { createServer } from 'node:http';
import { readFile, stat } from 'node:fs/promises';
import { join, normalize, extname } from 'node:path';
const ROOT = process.cwd();
const PORT = Number(process.env.PORT) || ${APP_PORT};
const TYPES = {
  '.html': 'text/html; charset=utf-8', '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8', '.mjs': 'text/javascript; charset=utf-8',
  '.json': 'application/json; charset=utf-8', '.svg': 'image/svg+xml',
  '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.gif': 'image/gif',
  '.webp': 'image/webp', '.ico': 'image/x-icon', '.woff2': 'font/woff2', '.txt': 'text/plain; charset=utf-8',
};
async function resolve(urlPath) {
  const clean = normalize(decodeURIComponent(urlPath.split('?')[0])).replace(/^(\\.\\.[/\\\\])+/, '');
  let p = join(ROOT, clean);
  try {
    if ((await stat(p)).isDirectory()) p = join(p, 'index.html');
    return p;
  } catch {
    return join(ROOT, 'index.html'); // SPA fallback
  }
}
createServer(async (req, res) => {
  try {
    const file = await resolve(req.url || '/');
    const body = await readFile(file);
    res.writeHead(200, { 'content-type': TYPES[extname(file)] || 'application/octet-stream' });
    res.end(body);
  } catch {
    res.writeHead(404, { 'content-type': 'text/plain' });
    res.end('not found');
  }
}).listen(PORT, '0.0.0.0', () => console.log('280 static server on', PORT));
`;
const IGNORE_DIRS = new Set([
  'node_modules',
  '.git',
  '.next',
  '.280',
  '.vercel',
  '.turbo',
  '.cache',
]);
function skipRepo(rel: string, isDir: boolean): boolean {
  const base = rel.split('/').pop() ?? '';
  if (isDir) return IGNORE_DIRS.has(base);
  return base === '.env' || base.startsWith('.env.');
}
function gitIgnoredEntries(root: string): Set<string> {
  try {
    const out = execFileSync(
      'git',
      ['-C', root, 'ls-files', '--others', '--ignored', '--exclude-standard', '--directory'],
      { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] },
    );
    return new Set(out.split('\n').filter(Boolean).map((p) => p.replace(/\/$/, '')));
  } catch {
    return new Set();
  }
}
function repoSkip(root: string): {
  skip: (rel: string, isDir: boolean) => boolean;
  skipped: string[];
} {
  const ignored = gitIgnoredEntries(root);
  const skipped: string[] = [];
  const skip = (rel: string, isDir: boolean): boolean => {
    if (skipRepo(rel, isDir)) return true;
    if (ignored.has(rel)) {
      skipped.push(isDir ? rel + '/' : rel);
      return true;
    }
    return false;
  };
  return { skip, skipped };
}
function skippedNote(skipped: string[]): string[] {
  if (skipped.length === 0) return [];
  const shown = skipped.slice(0, 10);
  const more = skipped.length - shown.length;
  const list = shown.join(', ') + (more > 0 ? `, +${more} more` : '');
  return [`not uploaded (gitignored): ${list}`];
}
function addGenerated(
  files: BlobInfo[],
  content: Map<Digest, Uint8Array>,
  path: string,
  text: string,
): void {
  const data = new TextEncoder().encode(text);
  const dig = digestBytes(data);
  content.set(dig, data);
  files.push({ path, digest: dig, size: data.length });
}
function assemble(
  files: BlobInfo[],
  content: Map<Digest, Uint8Array>,
  builder: string,
  notes: string[],
  policy: Policy280 = EMPTY_POLICY,
): Bundle {
  if (files.length === 0) {
    fail('the build context is empty', 'build your app first, then run two80 push again');
  }
  const manifest: Manifest = {
    kind: MANIFEST_KIND_CONTAINER,
    build: { builder, dockerfile: 'Dockerfile', port: APP_PORT },
    files,
    egress: policy.egress,
    access: policy.access,
    roles: policy.roles,
    routes: policy.routes,
    secrets: policy.secrets,
    config: policy.config,
    integrations: policy.integrations,
  };
  const extra: string[] = [];
  if (policy.access !== 'invited') {
    extra.push(`access: ${policy.access}`);
  }
  extra.push(...configDisclosure(policy.config));
  extra.push(...integrationDisclosure(policy.integrations));
  const diff = routeGateDiff(discoverNextRoutes(files.map((f) => f.path)), policy.routes);
  return { manifest, content, notes: [...notes, ...extra, ...diff] };
}
export function integrationDisclosure(integrations: IntegrationRequirement[]): string[] {
  if (integrations.length === 0) return [];
  const lines = ['integrations the app needs (bound to a resource in the dashboard; deploy waits until bound):'];
  for (const r of integrations) {
    lines.push(`  ${r.alias}  →  ${r.capability} [${r.operations.join(', ')}]`);
  }
  return lines;
}
export function configDisclosure(config: ConfigEntry[]): string[] {
  if (config.length === 0) return [];
  const lines = ['config the app reads (process.env), injected into the container:'];
  for (const c of config) {
    if (c.value === '') lines.push(`  ${c.name}  →  entered in the dashboard (deploy waits until set)`);
    else if (c.sensitive) lines.push(`  ${c.name}  →  set (sensitive; value hidden)`);
    else lines.push(`  ${c.name} = ${c.value}`);
  }
  return lines;
}
export function buildNextContainer(root: string): Bundle {
  if (!fileExists(join(root, 'package.json'))) {
    fail(
      'no package.json found for this Next.js project',
      'run two80 push from your app directory (the one with package.json)',
    );
  }
  const content = new Map<Digest, Uint8Array>();
  const policy = read280(root);
  const { skip, skipped } = repoSkip(root);
  if (fileExists(join(root, 'Dockerfile'))) {
    const files = walkContext(root, content, { skip });
    return assemble(
      files,
      content,
      'dockerfile',
      [
        'using your Dockerfile; your app must listen on port ' + APP_PORT,
        'to reach the 280 SDK API, install the Cloudflare CA in your entrypoint (' + CA_PATH + ')',
        ...skippedNote(skipped),
      ],
      policy,
    );
  }
  const files = walkContext(root, content, { skip });
  addGenerated(files, content, 'Dockerfile', NEXT_DOCKERFILE);
  addGenerated(files, content, ENTRYPOINT_PATH, ENTRYPOINT);
  const instrumentationNote = injectInstrumentation(root, files, content);
  return assemble(
    files,
    content,
    'next',
    [
      'generated a Dockerfile that builds and runs your Next.js app on port ' + APP_PORT,
      ...instrumentationNote,
      ...skippedNote(skipped),
    ],
    policy,
  );
}
function injectInstrumentation(
  root: string,
  files: BlobInfo[],
  content: Map<Digest, Uint8Array>,
): string[] {
  const usesSrcDir = dirExists(join(root, 'src', 'app')) || dirExists(join(root, 'src', 'pages'));
  const base = usesSrcDir ? 'src' : '';
  const existing = INSTRUMENTATION_NAMES.some(
    (n) => fileExists(join(root, n)) || fileExists(join(root, 'src', n)),
  );
  if (existing) return [];
  const path = base === '' ? INSTRUMENTATION_FILE : base + '/' + INSTRUMENTATION_FILE;
  addGenerated(files, content, path, INSTRUMENTATION);
  return [`added ${path} to log error digests with their stacks (two80 logs --digest)`];
}
export function buildStaticContainer(root: string, dir: string): Bundle {
  const content = new Map<Digest, Uint8Array>();
  const policy = read280(root);
  if (fileExists(join(dir, 'Dockerfile'))) {
    const files = walkContext(dir, content, { skip: skipRepo });
    return assemble(
      files,
      content,
      'dockerfile',
      ['using your Dockerfile; your app must listen on port ' + APP_PORT],
      policy,
    );
  }
  const files = walkContext(dir, content, { skip: skipRepo });
  addGenerated(files, content, 'server.280.mjs', STATIC_SERVER);
  addGenerated(files, content, 'Dockerfile', STATIC_DOCKERFILE);
  addGenerated(files, content, ENTRYPOINT_PATH, ENTRYPOINT);
  return assemble(
    files,
    content,
    'static',
    ['generated a container that serves your static site on port ' + APP_PORT],
    policy,
  );
}
