// The Next.js path: run the OpenNext adapter (.next/ into .open-next/), then
// wrangler `deploy --dry-run` to resolve worker.js and its imports into the one
// module the platform uploads. All preflight. Spec: next.go, normative incl pins.

import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdtempSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { basename, dirname, join, posix, resolve } from 'node:path';
import { gzipSync } from 'node:zlib';
import {
  MANIFEST_KIND_BUNDLE,
  MAX_WORKER_GZIP_BYTES,
  digestBytes,
  type BlobInfo,
  type Digest,
} from '@280/contracts';
import type { Bundle } from './static.js';
import { PreflightError, dirExists, fail, fileExists, walkAssets, walkFiles } from './walk.js';

// Pinned toolchain and runtime. Changing any invalidates the compatibility
// spike's results, so they move together or not at all.
const adapterPkg = '@opennextjs/cloudflare';
const adapterVersion = '1.20.2';
const wranglerPkg = 'wrangler';
const wranglerVersion = '4.113.0';
const compatibilityDate = '2026-07-23';

// What the adapter's worker needs from workerd: nodejs_compat for the Next
// server's Node built-ins, and global_fetch_strictly_public because the c3 Next
// template sets it and the spike's results only hold with it on.
const compatibilityFlags = ['nodejs_compat', 'global_fetch_strictly_public'];

const outputDirName = '.open-next';

export function buildNext(root: string): Bundle {
  requireNodeToolchain();
  requireNextBuild(root);
  const generated = ensureAdapterConfig(root);
  ensureAdapterInstalled(root);
  runAdapterBuild(root);

  const outDir = mkdtempSync(join(tmpdir(), '280-worker-'));
  try {
    runWranglerBundle(root, outDir);
    const worker = readBundledWorker(outDir);
    checkEnvelope(worker);
    checkNativeModules([join(root, outputDirName), outDir]);
    const b = nextBundle(join(root, outputDirName), worker);
    if (generated.length > 0) {
      b.notes.push(
        'generated ' +
          generated.join(' and ') +
          ' (yours now: commit, edit, or gitignore)',
      );
    }
    return b;
  } finally {
    rmSync(outDir, { recursive: true, force: true });
  }
}

// npm is how the pinned adapter/wrangler get into a project that lacks them.
export function requireNodeToolchain(): void {
  for (const bin of ['node', 'npm']) {
    if (!hasBin(bin)) {
      fail(
        'a Next.js push needs ' + bin + ' on PATH and it was not found',
        'install Node.js 20 or newer (https://nodejs.org), then run 280 push again',
      );
    }
  }
}

// 280 never runs `next build` itself: it is the developer's, with their env and
// exit code, and silently re-running it would hide their failures.
export function requireNextBuild(root: string): void {
  if (!fileExists(join(root, '.next', 'BUILD_ID'))) {
    fail(
      'no Next.js build found at .next (280 does not build your app for you)',
      'run npx next build, then run 280 push again',
    );
  }
  // The adapter needs the standalone tree, which `next build` only emits when the
  // app config asks; without this check it dies mid-build with a raw ENOENT.
  if (!dirExists(join(root, '.next', 'standalone'))) {
    fail(
      'the .next build has no standalone output, which the deploy adapter requires',
      'set output: "standalone" in next.config, run npx next build, then run 280 push again',
    );
  }
}

// Writes the adapter/wrangler config files, only when missing, into the project
// root (not a temp dir): open-next.config.ts imports the adapter by bare
// specifier, so it can only resolve from inside the project. Returns files created.
export function ensureAdapterConfig(root: string): string[] {
  const made: string[] = [];
  if (!findFirst(root, 'open-next.config.ts')) {
    const body =
      '// Generated by 280 because this project had none. Yours to keep, edit, or gitignore.\n' +
      'import { defineCloudflareConfig } from "' +
      adapterPkg +
      '";\n' +
      'import kvIncrementalCache from "' +
      adapterPkg +
      '/overrides/incremental-cache/kv-incremental-cache";\n' +
      '\n' +
      '// KV backs ISR. 280 attaches the NEXT_INC_CACHE_KV binding at activation\n' +
      '// and seeds it with the prerendered cache from this build.\n' +
      'export default defineCloudflareConfig({\n' +
      '\tincrementalCache: kvIncrementalCache,\n' +
      '});\n';
    writeConfig(join(root, 'open-next.config.ts'), body);
    made.push('open-next.config.ts');
  }
  // Mirror the adapter's own lookup: any one of these counts as configured.
  if (!findFirst(root, 'wrangler.jsonc', 'wrangler.json', 'wrangler.toml')) {
    const flags = '"' + compatibilityFlags.join('", "') + '"';
    const body =
      '// Generated by 280 because this project had none. Yours to keep, edit, or gitignore.\n' +
      '// No bindings are declared here on purpose: 280 attaches them at activation.\n' +
      '{\n' +
      '\t"name": "' +
      slug(root) +
      '",\n' +
      '\t"main": "' +
      outputDirName +
      '/worker.js",\n' +
      '\t"compatibility_date": "' +
      compatibilityDate +
      '",\n' +
      '\t"compatibility_flags": [' +
      flags +
      '],\n' +
      '\t"assets": { "binding": "ASSETS", "directory": "' +
      outputDirName +
      '/assets" }\n' +
      '}\n';
    writeConfig(join(root, 'wrangler.jsonc'), body);
    made.push('wrangler.jsonc');
  }
  return made;
}

function writeConfig(p: string, body: string): void {
  try {
    writeFileSync(p, body, { mode: 0o644 });
  } catch (err) {
    fail(
      'could not write ' + basename(p) + ': ' + errMessage(err),
      'check the project directory is writable, then run 280 push again',
    );
  }
}

function findFirst(root: string, ...names: string[]): boolean {
  return names.some((n) => fileExists(join(root, n)));
}

// Adapter and wrangler must be *in* the project (bare-specifier import), so
// `npx --package` cannot satisfy them. `npm install --no-save` adds them to
// node_modules leaving package.json/lock byte-identical.
export function ensureAdapterInstalled(root: string): void {
  const want: string[] = [];
  if (!fileExists(adapterCLI(root))) {
    want.push(adapterPkg + '@' + adapterVersion);
  }
  if (!fileExists(wranglerCLI(root))) {
    want.push(wranglerPkg + '@' + wranglerVersion);
  }
  if (want.length === 0) {
    return;
  }
  const args = ['install', '--no-save', '--no-audit', '--no-fund', ...want];
  const { out, ok } = run(root, 'npm', args);
  if (!ok) {
    fail(
      'could not install the Cloudflare adapter (' +
        want.join(' ') +
        '):\n' +
        tail(out, 20),
      'run npm install ' + want.join(' ') + ' in your project, then run 280 push again',
    );
  }
  // npm can exit 0 yet leave nothing usable (workspace root, ignore-scripts):
  // fail here rather than on a confusing exec error later.
  for (const p of [adapterCLI(root), wranglerCLI(root)]) {
    if (!fileExists(p)) {
      fail(
        'npm install finished but ' +
          basename(dirname(p)) +
          ' is still not present in node_modules',
        'run npm install ' +
          want.join(' ') +
          ' in your project and check it succeeds, then run 280 push again',
      );
    }
  }
}

function adapterCLI(root: string): string {
  return join(root, 'node_modules', '@opennextjs', 'cloudflare', 'dist', 'cli', 'index.js');
}

function wranglerCLI(root: string): string {
  return join(root, 'node_modules', 'wrangler', 'bin', 'wrangler.js');
}

// --skipNextBuild is the whole point: the developer's build already ran, and
// re-running it here would discard their environment.
export function runAdapterBuild(root: string): void {
  const { out, ok } = run(root, 'node', [adapterCLI(root), 'build', '--skipNextBuild']);
  if (!ok) {
    fail(
      'the Cloudflare adapter could not build this Next.js app:\n' + tail(out, 25),
      'fix the error above, or run npx opennextjs-cloudflare build in your project to see it in full',
    );
  }
}

// Dry run only: resolves worker.js and its imports into one module; nothing is
// uploaded and no credentials are used.
export function runWranglerBundle(root: string, outDir: string): void {
  const { out, ok } = run(root, 'node', [
    wranglerCLI(root),
    'deploy',
    '--dry-run',
    '--outdir',
    outDir,
  ]);
  if (!ok) {
    fail(
      'wrangler could not bundle the worker:\n' + tail(out, 25),
      'fix the error above, or run npx wrangler deploy --dry-run in your project to see it in full',
    );
  }
}

// Picks the one module the platform uploads. Sourcemaps and wrangler's README are
// skipped; any other leftover is a module the platform cannot carry, so it is
// named and refused rather than left to a runtime "module not found".
export function readBundledWorker(outDir: string): Uint8Array {
  let entries;
  try {
    entries = readdirSync(outDir, { withFileTypes: true });
  } catch (err) {
    return fail(
      'could not read the bundled worker: ' + errMessage(err),
      'run 280 push again',
    );
  }
  let entry = '';
  const extra: string[] = [];
  for (const e of entries) {
    const name = e.name;
    if (e.isDirectory() || name.endsWith('.map') || name === 'README.md') {
      continue;
    }
    if (name === 'worker.js') {
      entry = name;
      continue;
    }
    extra.push(name);
  }
  let leftover = extra;
  if (entry === '' && leftover.length === 1) {
    entry = leftover[0]!;
    leftover = [];
  }
  if (entry === '') {
    fail(
      'wrangler produced no worker module to upload',
      'run npx wrangler deploy --dry-run in your project and check it emits a bundled worker',
    );
  }
  if (leftover.length > 0) {
    fail(
      'this app needs extra worker modules that 280 cannot attach yet: ' +
        leftover.join(', '),
      'remove the dependency that pulls in ' +
        leftover[0] +
        ' (commonly a WebAssembly package), then run 280 push again',
    );
  }
  try {
    return readFileSync(join(outDir, entry));
  } catch (err) {
    return fail(
      'could not read the bundled worker: ' + errMessage(err),
      'run 280 push again',
    );
  }
}

// Cloudflare measures the Worker size limit on the gzipped script. The manifest
// carries raw sizes, so this is the only place the real check can run.
export function checkEnvelope(worker: Uint8Array): void {
  let gz: Buffer;
  try {
    gz = gzipSync(worker, { level: 9 });
  } catch (err) {
    fail(
      "could not measure the worker's compressed size: " + errMessage(err),
      'run 280 push again',
    );
  }
  envelopeError(worker.length, gz.length);
}

// The decision alone, so the limit message is testable without ten megabytes of
// incompressible bytes.
export function envelopeError(raw: number, gz: number): void {
  if (gz <= MAX_WORKER_GZIP_BYTES) {
    return;
  }
  fail(
    'the bundled worker is ' +
      mib(gz) +
      ' gzipped (' +
      mib(raw) +
      " uncompressed), over Cloudflare's " +
      mib(MAX_WORKER_GZIP_BYTES) +
      ' limit',
    'move large dependencies or embedded data out of server code and into static assets, then run 280 push again',
  );
}

function mib(n: number): string {
  return (n / (1 << 20)).toFixed(1) + ' MiB';
}

// Workers run V8 isolates, not Node, so a compiled .node addon can never load; it
// would otherwise surface as an opaque runtime crash on the first request.
export function checkNativeModules(dirs: string[]): void {
  const found: string[] = [];
  for (const dir of dirs) {
    if (!dirExists(dir)) {
      continue;
    }
    for (const { abs } of walkFiles(dir)) {
      if (abs.endsWith('.node')) {
        found.push(nativeModuleOwner(abs));
      }
    }
  }
  if (found.length === 0) {
    return;
  }
  const owners = dedupe(found);
  fail(
    'this app depends on native Node modules, which Cloudflare Workers cannot run: ' +
      owners.join(', '),
    'replace ' +
      owners[0] +
      ' with a pure-JavaScript equivalent, or keep it out of server code, then run 280 push again',
  );
}

// Names the dependency an addon belongs to (the actionable thing), falling back
// to the file when it is not under a node_modules tree.
function nativeModuleOwner(p: string): string {
  const parts = p.split(/[\\/]/);
  for (let i = parts.length - 1; i >= 0; i--) {
    if (parts[i] !== 'node_modules' || i + 1 >= parts.length) {
      continue;
    }
    if (parts[i + 1]!.startsWith('@') && i + 2 < parts.length) {
      return parts[i + 1] + '/' + parts[i + 2];
    }
    return parts[i + 1]!;
  }
  return basename(p);
}

function dedupe(input: string[]): string[] {
  const seen = new Set<string>();
  const out: string[] = [];
  for (const s of input) {
    if (!seen.has(s)) {
      seen.add(s);
      out.push(s);
    }
  }
  return out;
}

// Split from buildNext so the manifest shape is testable against a fixture, with
// no adapter and no network.
export function nextBundle(outputDir: string, worker: Uint8Array): Bundle {
  const content = new Map<Digest, Uint8Array>();

  const wd = digestBytes(worker);
  content.set(wd, worker);

  let assets: BlobInfo[];
  try {
    assets = walkAssets(join(outputDir, 'assets'), content);
  } catch (err) {
    return fail(
      "could not read the adapter's static assets: " + errMessage(err),
      'delete .open-next and run 280 push again',
    );
  }

  const cache = walkCache(join(outputDir, 'cache'), content);

  return {
    manifest: {
      kind: MANIFEST_KIND_BUNDLE,
      worker: { path: '', digest: wd, size: worker.length },
      assets,
      cache,
    },
    content,
    notes: [],
  };
}

// The adapter's DEFAULT_PREFIX. 280 never sets NEXT_INC_CACHE_KV_PREFIX, so the
// running worker derives the same prefix when it reads these entries back.
const cachePrefix = 'incremental-cache';

// Maps the adapter's prerendered cache into the KV keys the platform writes at
// activation, mirroring the pinned adapter's populateCache exactly: a mismatch is
// invisible, every ISR page would silently miss and re-render.
export function walkCache(
  cacheDir: string,
  content: Map<Digest, Uint8Array>,
): BlobInfo[] {
  if (!existsSync(cacheDir)) {
    return []; // no ISR or prerendered pages; nothing to seed
  }
  const out: BlobInfo[] = [];
  let files;
  try {
    files = [...walkFiles(cacheDir)];
  } catch (err) {
    if (err instanceof PreflightError) {
      throw err;
    }
    return fail(
      "could not read the adapter's prerendered cache: " + errMessage(err),
      'delete .open-next and run 280 push again',
    );
  }
  for (const { abs, rel } of files) {
    const key = cacheKey(rel); // throws PreflightError on an unknown shape
    let data: Buffer;
    try {
      data = readFileSync(abs);
    } catch (err) {
      return fail(
        "could not read the adapter's prerendered cache: " + errMessage(err),
        'delete .open-next and run 280 push again',
      );
    }
    const dig = digestBytes(data);
    content.set(dig, data);
    out.push({ path: key, digest: dig, size: data.length });
  }
  return out;
}

export function cacheKey(rel: string): string {
  let route: string;
  let buildID: string;
  let cacheType: string;
  if (rel.startsWith('__fetch')) {
    const parts = rel.split('/');
    if (parts[0] !== '__fetch' || parts.length < 3) {
      return unexpectedCacheFile(rel);
    }
    buildID = parts[1]!;
    route = '/' + posix.join(...parts.slice(2));
    cacheType = 'fetch';
  } else {
    if (!rel.endsWith('.cache')) {
      return unexpectedCacheFile(rel);
    }
    const parts = rel.slice(0, -'.cache'.length).split('/');
    if (parts.length < 2) {
      return unexpectedCacheFile(rel);
    }
    buildID = parts[0]!;
    route = '/' + posix.join(...parts.slice(1));
    cacheType = 'cache';
  }
  const sum = createHash('sha256').update(route).digest('hex');
  return collapseSlashes(cachePrefix + '/' + buildID + '/' + sum + '.' + cacheType);
}

function unexpectedCacheFile(rel: string): never {
  return fail(
    'the adapter produced a cache file 280 does not recognize: .open-next/cache/' +
      rel,
    'delete .open-next and run 280 push again; if it persists, your @opennextjs/cloudflare version is newer than the one 280 supports (' +
      adapterVersion +
      ')',
  );
}

function collapseSlashes(s: string): string {
  while (s.includes('//')) {
    s = s.replaceAll('//', '/');
  }
  return s;
}

// Default app name for a generated wrangler config: package.json "name" else the
// dir name, slugified. Kept local (no detect dependency); only names a generated
// config file, never part of the manifest.
function slug(root: string): string {
  const name = packageName(root);
  if (name) {
    return slugify(name);
  }
  return slugify(basename(resolve(root)));
}

function packageName(root: string): string | undefined {
  try {
    const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')) as {
      name?: unknown;
    };
    return typeof pkg.name === 'string' ? pkg.name : undefined;
  } catch {
    return undefined;
  }
}

function slugify(s: string): string {
  s = s.trim().toLowerCase();
  if (s.startsWith('@')) {
    s = s.slice(1); // npm scope leader
  }
  s = s.replace(/[^a-z0-9]+/g, '-');
  s = s.replace(/^-+|-+$/g, '');
  return s === '' ? 'app' : s;
}

// True only for npm on Windows (an npm.cmd shim): Node refuses to spawn a .cmd
// without shell:true (CVE-2024-27980). node is a plain .exe, spawned directly.
function needsShell(name: string): boolean {
  return process.platform === 'win32' && name === 'npm';
}

// Returns combined output (the useful thing when a build tool fails). CI=1 keeps
// the adapter from waiting on a prompt no agent will ever answer.
function run(
  dir: string,
  name: string,
  args: string[],
): { out: string; ok: boolean } {
  const res = spawnSync(name, args, {
    cwd: dir,
    env: { ...process.env, CI: '1' },
    encoding: 'utf8',
    shell: needsShell(name),
  });
  const out = (res.stdout ?? '') + (res.stderr ?? '');
  const ok = !res.error && res.status === 0;
  return { out, ok };
}

// Whether a binary is on PATH; `--version` also exercises the Windows .cmd shim.
function hasBin(name: string): boolean {
  const res = spawnSync(name, ['--version'], {
    stdio: 'ignore',
    shell: needsShell(name),
  });
  return !res.error && res.status === 0;
}

// Last n non-empty lines, where build tools put the error; the whole log buries it.
export function tail(s: string, n: number): string {
  const lines: string[] = [];
  for (const l of s.replaceAll('\r\n', '\n').split('\n')) {
    if (l.trim() !== '') {
      lines.push(l.replace(/[ \t]+$/, ''));
    }
  }
  const kept = lines.length > n ? lines.slice(lines.length - n) : lines;
  return kept.join('\n');
}

function errMessage(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}

// Re-exported so tests assert the pinned identifiers against one source of truth.
export {
  adapterPkg,
  adapterVersion,
  wranglerPkg,
  wranglerVersion,
  compatibilityDate,
  compatibilityFlags,
  outputDirName,
  collapseSlashes,
  slug,
};
